# 应用配置
app:

# VAD 服务配置
vad:
  model_name: "iic/speech_fsmn_vad_zh-cn-16k-common-pytorch"
  model_revision: "v2.0.4"
  device: "auto"
  # 可以在这里添加更多VAD相关配置
  params:
    max_end_silence_time: 300    # 尾部静音超时（ms）
    speech_noise_thres: 0.4     # 语音/噪音阈值（0~1）

# KWS 服务配置
kws:
  model_name: "iic/speech_charctc_kws_phone-xiaoyun"
  device: "cpu"
  # 可以在这里添加更多KWS相关配置

# ASR 服务配置
asr:
  model_name: "iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online"
  model_revision: "v2.0.4"
  device: "cuda"
  # 可以在这里添加更多ASR相关配置
  params:
    chunk_size: 5  # 流式处理的块大小
